#!/bin/bash
# Generate .env.local from local Supabase status
# Usage: ./scripts/setup-local-env.sh

set -e

# Check if supabase is running
if ! supabase status --output json > /dev/null 2>&1; then
    echo "Error: Supabase is not running. Start it with: npm run supabase:start"
    exit 1
fi

# Get status as JSON
STATUS=$(supabase status --output json 2>/dev/null)

# Extract values
API_URL=$(echo "$STATUS" | grep -o '"API_URL": *"[^"]*"' | cut -d'"' -f4)
ANON_KEY=$(echo "$STATUS" | grep -o '"ANON_KEY": *"[^"]*"' | cut -d'"' -f4)
SERVICE_ROLE_KEY=$(echo "$STATUS" | grep -o '"SERVICE_ROLE_KEY": *"[^"]*"' | cut -d'"' -f4)

if [ -z "$API_URL" ] || [ -z "$ANON_KEY" ] || [ -z "$SERVICE_ROLE_KEY" ]; then
    echo "Error: Could not extract keys from supabase status"
    exit 1
fi

# Check for existing .env.local and preserve non-Supabase vars
ENV_LOCAL=".env.local"
PRESERVED_VARS=""

if [ -f "$ENV_LOCAL" ]; then
    echo "Found existing .env.local, preserving non-Supabase variables..."
    # Extract lines that don't start with NEXT_PUBLIC_SUPABASE or SUPABASE_SERVICE
    PRESERVED_VARS=$(grep -v '^NEXT_PUBLIC_SUPABASE_URL=' "$ENV_LOCAL" | \
                     grep -v '^NEXT_PUBLIC_SUPABASE_ANON_KEY=' | \
                     grep -v '^SUPABASE_SERVICE_ROLE_KEY=' | \
                     grep -v '^#.*[Ll]ocal [Ss]upabase' | \
                     grep -v '^$' || true)
fi

# Write new .env.local
cat > "$ENV_LOCAL" << EOF
# Local Supabase (generated by scripts/setup-local-env.sh)
NEXT_PUBLIC_SUPABASE_URL=$API_URL
NEXT_PUBLIC_SUPABASE_ANON_KEY=$ANON_KEY
SUPABASE_SERVICE_ROLE_KEY=$SERVICE_ROLE_KEY
EOF

# Append preserved variables if any
if [ -n "$PRESERVED_VARS" ]; then
    echo "" >> "$ENV_LOCAL"
    echo "# Preserved from previous .env.local" >> "$ENV_LOCAL"
    echo "$PRESERVED_VARS" >> "$ENV_LOCAL"
fi

echo "Created .env.local with local Supabase credentials"
echo ""
echo "Local Supabase URLs:"
echo "  API:    $API_URL"
echo "  Studio: http://127.0.0.1:54323"
echo ""
echo "Test credentials: test@example.com / password123"
echo ""
echo "To switch back to production: rm .env.local"
